true := "true"

build:
    cargo build

rebuild:
    cargo clean
    cargo build

# tests-ci with rebuild? true|false, default is true
tests-ci rebuild=true:
    #!/usr/bin/env sh
    if {{rebuild}}; then
        cargo clean
        cargo build
    fi

    cargo test -- --test-threads=1

test TEST: rebuild
    cargo test {{TEST}}